version: '3'
services:
  postgres:
    image: postgres:9.6.8-alpine
    restart: unless-stopped
    ports:
    - 15432:5432
    environment:
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: